import {
  HiOutlineCurrencyDollar,
  HiOutlineStar,
  HiOutlineWallet,
  HiOutlineCreditCard,
  HiOutlineBookOpen,
  HiOutlineEnvelope,
  HiOutlineShoppingBag,
  HiOutlineArrowsUpDown,
  HiOutlineBolt,
  HiOutlineBuildingOffice2,
  HiOutlinePresentationChartBar,
  HiOutlineShieldCheck,
  HiOutlineRectangleStack,
  HiOutlineArrowsRightLeft,
  HiOutlineGlobeAlt,
  HiOutlineCube,
  HiOutlineCloud,
  HiOutlineCodeBracket,
  HiOutlineBanknotes,
  HiOutlineCircleStack,
  HiOutlineBeaker,
  HiOutlineInformationCircle,
  HiOutlineDocumentText,
  HiOutlineUserGroup,
  HiOutlineArrowTrendingUp,
  HiOutlineScale,
  HiOutlineAdjustmentsHorizontal,
} from 'react-icons/hi2'

export const ICONS = {
  buySell:      HiOutlineCurrencyDollar,
  coinbaseOne:  HiOutlineStar,
  wallet:       HiOutlineWallet,
  card:         HiOutlineCreditCard,
  book:         HiOutlineBookOpen,
  mail:         HiOutlineEnvelope,
  shoppingBag:  HiOutlineShoppingBag,
  arrowUpDown:  HiOutlineArrowsUpDown,
  lightning:    HiOutlineBolt,
  building:     HiOutlineBuildingOffice2,
  chartBars:    HiOutlinePresentationChartBar,
  shield:       HiOutlineShieldCheck,
  layers:       HiOutlineRectangleStack,
  exchange:     HiOutlineArrowsRightLeft,
  globe:        HiOutlineGlobeAlt,
  cube:         HiOutlineCube,
  cloud:        HiOutlineCloud,
  code:         HiOutlineCodeBracket,
  paySdk:       HiOutlineBanknotes,
  database:     HiOutlineCircleStack,
  atom:         HiOutlineBeaker,
  info:         HiOutlineInformationCircle,
  document:     HiOutlineDocumentText,
  users:        HiOutlineUserGroup,
  trendingUp:   HiOutlineArrowTrendingUp,
  scales:       HiOutlineScale,
  sliders:      HiOutlineAdjustmentsHorizontal,
}
